"""Generate the area-information knowledge document from the real dataset statistics."""
import pandas as pd
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
df = pd.read_csv(ROOT / "data/properties_clean.csv")
NAMES = {"Blmngtn":"Bloomington Heights","Blueste":"Bluestem","BrDale":"Briardale","BrkSide":"Brookside","ClearCr":"Clear Creek",
 "CollgCr":"College Creek","Crawfor":"Crawford","Edwards":"Edwards","Gilbert":"Gilbert","IDOTRR":"Iowa DOT and Rail Road","MeadowV":"Meadow Village",
 "Mitchel":"Mitchell","NAmes":"North Ames","NoRidge":"Northridge","NPkVill":"Northpark Villa","NridgHt":"Northridge Heights","NWAmes":"Northwest Ames",
 "OldTown":"Old Town","SWISU":"South and West of Iowa State University","Sawyer":"Sawyer","SawyerW":"Sawyer West","Somerst":"Somerset",
 "StoneBr":"Stone Brook","Timber":"Timberland","Veenker":"Veenker"}
g = df.groupby("Neighborhood").agg(n=("SalePrice","size"), price=("SalePrice","median"), ppsf=("PricePerSqft","median"),
    year=("YearBuilt","median"), qual=("OverallQual","median"), sqft=("GrLivArea","median"), beds=("BedroomAbvGr","median"),
    garage=("GarageCars","median")).sort_values("price", ascending=False)
q1, q3 = g.price.quantile(.33), g.price.quantile(.67)
tier = lambda p: "premium" if p >= q3 else ("mid-market" if p >= q1 else "affordable")
city_med, city_ppsf = df.SalePrice.median(), df.PricePerSqft.median()
L = ["# Ames, Iowa: Area Information and Neighborhood Guide", "",
 "*Generated by PropMind from the Ames housing dataset of 1,458 home sales recorded between 2006 and 2010. Figures are historical medians, useful for comparing areas against each other, not current market quotes.*", "",
 "## 1. City Overview", "",
 f"Ames is a university city in Story County, Iowa, and the home of Iowa State University, which strongly shapes housing demand, especially for rentals near campus. Across the dataset the median sale price is ${city_med:,.0f} and the median price per square foot of living area is ${city_ppsf:,.0f}. Prices vary widely by neighborhood: the premium areas sell at more than double the price of the most affordable ones.", "",
 "## 2. How Neighborhoods Compare", "",
 f"Neighborhoods are grouped into three tiers by median price. **Premium** areas have a median above ${q3:,.0f}, **mid-market** areas fall between ${q1:,.0f} and ${q3:,.0f}, and **affordable** areas are below ${q1:,.0f}. Premium neighborhoods typically combine newer construction, higher build quality and larger homes. Affordable neighborhoods are mostly older homes closer to the center or the campus, where purchase prices are low but condition and repair needs deserve a careful inspection.", "",
 "## 3. Price Ranking at a Glance", ""]
for i, (k, r) in enumerate(g.iterrows(), 1):
    L.append(f"{i}. {NAMES.get(k,k)} ({k}): median ${r.price:,.0f}, ${r.ppsf:,.0f} per sqft, {int(r.n)} sales.")
L += ["", "## 4. Neighborhood Profiles", ""]
for k, r in g.iterrows():
    diff = (r.price / city_med - 1) * 100
    rel = f"{abs(diff):.0f}% {'above' if diff >= 0 else 'below'} the city median"
    age = "recently built" if r.year >= 2000 else ("built in the 1990s" if r.year >= 1990 else ("built mostly in the 1970s and 1980s" if r.year >= 1970 else "older housing stock"))
    L += [f"### {NAMES.get(k,k)} ({k})", "",
          f"{NAMES.get(k,k)} is a {tier(r.price)} area with {int(r.n)} sales in the data. The median sale price is ${r.price:,.0f}, which is {rel}, at about ${r.ppsf:,.0f} per square foot. The typical home was built around {int(r.year)} ({age}), has about {r.sqft:,.0f} square feet of living space, {int(r.beds)} bedrooms, space for {int(r.garage)} car(s), and a median overall quality score of {int(r.qual)} out of 10.", ""]
L += ["## 5. Which Area Suits Which Buyer", "",
 "- **First-time or budget buyers:** look at the affordable tier and budget for inspection and repairs on older homes.",
 "- **Families wanting space and newer construction:** the mid-market and premium neighborhoods with recent build years offer larger homes and more garage space.",
 "- **Luxury and quality-focused buyers:** the premium tier has the highest quality scores and price per square foot.",
 "- **Investors:** compare median price with expected rent; the affordable tier gives a lower entry price, while premium areas tend to hold value but yield less per dollar invested.", "",
 "## 6. What Drives Price in Ames", "",
 "In the dataset the strongest drivers of price are overall build quality, living area, garage capacity, total basement size and the year built. Neighborhood adds a large premium or discount on top of these. Use the PropMind price predictor to see how changing one feature, such as quality or area, changes the estimate for a specific home.", ""]
(ROOT / "docs/area_information.md").write_text("\n".join(L))
print(len("\n".join(L).split()), "words;", g.shape[0], "neighborhoods")
